// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBNbvRQSKd6yaIOhulAT1bO7pJ-7nzK0',
    appId: '1:788131250494:android:c0e60820a2417134e06c6f',
    messagingSenderId: '788131250494',
    projectId: 'nit-goa-gate-system',
    storageBucket: 'nit-goa-gate-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97MWySUoJXY_wKeglj94MKDv6xyfxNXM',
    appId: '1:788131250494:ios:8ba17a0784881d14e06c6f',
    messagingSenderId: '788131250494',
    projectId: 'nit-goa-gate-system',
    storageBucket: 'nit-goa-gate-system.firebasestorage.app',
    iosClientId: '788131250494-1t780n9bmeqo8hs0p8qrfa0g2u9e94qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nitGoaGateApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxkQrj3aqQVvUVgsAD2IvbNwFtnBA5Zk',
    appId: '1:788131250494:web:d21d8ff23ad4624be06c6f',
    messagingSenderId: '788131250494',
    projectId: 'nit-goa-gate-system',
    authDomain: 'nit-goa-gate-system.firebaseapp.com',
    storageBucket: 'nit-goa-gate-system.firebasestorage.app',
    measurementId: 'G-LJYF38PZMQ',
  );

}